### ISSUE TITLE
in the error message about possible values, hide call.

### ISSUE THREAD

**Issue by maelle** [lifewatch/eurobis#19]
The error message you showed showed `build_life_traits()` that the user does not know so hide the info?

**Comment by salvafern** [comment]
Not sure how to do this, sorry 😞 `eurobis_occurrences()` calls `build_viewparams()`, and this one calls `build_life_traits()`

**Comment by maelle** [comment]
e.g. if using `stop()` one can use `stop(blablabla, call. = FALSE)`

**Comment by salvafern** [comment]
🤦‍♂️ Didn't see that. Thanks @maelle ! Should be fixed now
