### ISSUE TITLE
Package failures due to migration of EMODnet to Central Portal

### ISSUE THREAD

**Issue by salvafern** [lifewatch/eurobis#24]
As a result of the migration of EMODnet Biology, in which this package heavily relied, to the EMODnet Central Portal, some services of this package are failing. 

See https://emodnet.ec.europa.eu/en/one-ocean-one-emodnet-european-marine-observation-and-data-network-emodnet-launches-its-fully

* No overviews of datasets, regions and traits available. They all redirect to `https://emodnet.ec.europa.eu/geoviewer/`
   * `https://www.emodnet-biology.eu/toolbox/en/download/datasets` : `eurobis_list_datasets()`
   * `https://www.emodnet-biology.eu/toolbox/en/download/regions` : `eurobis_list_regions()`
   * `https://www.emodnet-biology.eu/toolbox/en/download/traits` : `eurobis_list_traits()`

I'll update this issue as I discover more

**Comment by LennertSchepers** [comment]
Hi @salvafern fyi the toolbox has moved to https://www.eurobis.org/toolbox/en/download/occurrence/explore, maybe change the url?
