### ISSUE TITLE
Failing to download occurrence data using eurobis_occurrences()

### ISSUE THREAD

**Issue by johannow** [lifewatch/eurobis#29]
Re-running some code using the eurobis_occurrences() gives the following error, while it was able to run a couple of weeks ago.

<img width="610" alt="Schermafbeelding 2024-01-02 134446" src="https://github.com/lifewatch/eurobis/assets/148065786/30a033fd-00fc-42a0-8ceb-2b694085bd2a">

**Comment by bart-v** [comment]
@salvafern API issue or R issue?

**Comment by bart-v** [comment]
A problem with the API
The issue should be fixed, can you confirm?

**Comment by johannow** [comment]
Yes it works again, thanks!
