### ISSUE TITLE
getEurobisGrid, getEurobisPoints implement same variables as getEurobisData

### ISSUE THREAD

**Issue by LennertSchepers** [lifewatch/eurobis#6]
currently the getEurobisGrid and getEurobisPoints only can have the Aphia (and grid size) as input, but it should be good to have the same possibilities as the getEurobisData function:

- geourl
- aphiaid
- speciesgroup
- mrgid
- startyear
- endyear
- type

and somewhere specify in the function/examples how they can retrieve from which datasets these data come from.

**Comment by LennertSchepers** [comment]
@salvafern you removed the eurobis grid/points functions from the package?

**Comment by salvafern** [comment]
Yes I removed the functions of the old package. It was a quick fix to make the package be more robust towards the EBR workshop. I can restore the old functions of even better, write new ones. But I wonder if the grid functions are that necessary. In my opinion these are useful only as a visualization tool - therefore we should rather visualize via WMS. 

I'm not sure we can offer all the possibilities to query on. There are some limitations with this layer. Better to discuss internally.

**Comment by salvafern** [comment]
To be continued in https://github.com/lifewatch/eurobis/issues/22

As I said, the grid layers don't allow to query on all those filters. Only on dataset and aphiaid.
